### PR TITLE
seraphim is already the plural form of seraph

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Uh, dude, this is the King James Version of the Bible.

**Comment by 31ias** [comment]
I don't know why I thought it was necessary to make a pull request for my personal NITPICK of our gay boy James' own **TRANSLATION**

Dumb.

Install dragora gnu/linux libre or jehanneOS

**Comment by 31ias** [comment]
I don't know why I thought it was necessary to make a pull request for my own personal NITPICK of our gayboi James' TRANSLATION

Dumb.

Install dragora gnu/linux libre or jehanneOS

**Comment by ghost** [comment]
> Uh, dude, this is the King James Version of the Bible.

https://github.com/LukeSmithxyz/kjv/commit/b92b7622285d10464f9274f11e740bef90705bbc

And a pre 1**666** KJV at that 

xd

**Pull request closed without merging**
